### ISSUE TITLE
Mentions "templates" in notes about metering labels.

### ISSUE THREAD

**Issue by jmesnil** [redhat-documentation/mw-shared-modules#21]
Hi,

We are adding the metering labels to the OpenShift Templates that deploys EAP applications.
Would it be possible to amend the note in https://github.com/redhat-documentation/mw-shared-modules/blob/master/runtimes-common/ref_runtimes_metering_labels.adoc and replace:

> Do not add metering labels to any pods that an operator deploys and manages.

by

> Do not add metering labels to any pods that an operator or a template deploys and manages.

**Comment by oraNod** [comment]
@jmesnil Sounds fine to me, Jeff. I've opened a PR, please feel free to leave a comment there.

**Comment by oraNod** [comment]
@jmesnil changes synced to EAP with these commits:

https://gitlab.cee.redhat.com/red-hat-jboss-enterprise-application-platform-documentation/eap-release-notes/-/commit/325e6bf97b83a1657523f832485d9f4f6a072128

https://gitlab.cee.redhat.com/red-hat-jboss-enterprise-application-platform-documentation/eap-release-notes/-/commit/45fa7c3cde97d8681394c7a4abcae0eccc1e36e5
