### ISSUE TITLE
Red Hat Runtimes attribute

### ISSUE THREAD

**Issue by oraNod** [redhat-documentation/mw-shared-modules#23]
Need to use "Runtimes" as a product offering in docs in a way that matches customer expectation.

Example: "For integration with the Red Hat Runtimes portfolio or other Red Hat solutions or services, you should configure Data Grid caches with Protobuf encoding."

**Comment by oraNod** [comment]
@ncbaratta Could you please check with John to get the language here and I'll add it to runtimes common?

**Comment by ncbaratta** [comment]
Good to Go!

**Comment by oraNod** [comment]
thanks @ncbaratta !
